//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hastalar
    {
        public int Id { get; set; }
        public string Hasta_ad { get; set; }
        public string Hasta_soyad { get; set; }
        public string HastaTC { get; set; }
        public string Hasta_cinsiyet { get; set; }
        public Nullable<System.DateTime> Hasta_dogum_tarih { get; set; }
        public string Hasta_mail { get; set; }
        public string Hasta_telefon { get; set; }
        public string Hasta_sifre { get; set; }
    }
}
