//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personeller
    {
        public int Id { get; set; }
        public string Personel_ad { get; set; }
        public string Personel_soyad { get; set; }
        public string Personel_TC { get; set; }
        public string Personel_cinsiyet { get; set; }
        public Nullable<System.DateTime> Personel_dogum_tarih { get; set; }
        public string Personel_mail { get; set; }
        public string Personel_telefon { get; set; }
        public string Personel_sifre { get; set; }
    }
}
